- tortoise/utils/audio.py
The read.py script did not work with pth latents, so I fixed the bug in audio.py. It seems that in the elif statement, instead of voice, voices should be clip, clips. And torch stack doesn't work with tuples, so I had to split this operation.
> Fix bug in load_voices in audio.py

- tortoise/api.py
- tortoise/do_tts.py
- tortoise/read.py
- tortoise/utils/audio.py
This allows you to specify an alternative storage location for the models via the `TORTOISE_MODELS_DIR` environment variable. It also adds a `extra_voice_dirs` argument to the voice loading functions that allows you to specify additional directories of voices.
> Make models dir configurable

- tortoise/api.py
- tortoise/do_tts.py
- tortoise/models/cvvp.py
This add the CVVP model back and defaults it to off. I renamed the parameter to control it from `clvp_cvvp_slider` to `cvvp_amount` since it was a bit counter intuitive to use when it can be disabled.
Fixes #62
> Revive CVVP model

- tortoise/utils/wav2vec_alignment.py
Thanks to Python's handling of mutable default arguments, having `record` default to an empty dict means that text can stick around from previous calls if you're calling the aligner in a loop (as I was). This can be avoided by creating a new dict inside the function where necessary.
Just noticed issue #65 — this might be the root cause there if multi-line inputs are the problem.
> avoid mutable default in aligner

- scripts/tortoise_tts.py
- setup.py
- tortoise/api.py
- tortoise/models/arch_util.py
- tortoise/utils/audio.py
- tortoise/utils/tokenizer.py
This adds a GNU-style CLI for TorToiSe that exposes most of the tuning knobs available and combines the functionality of do_tts.py and read.py.
```
usage: tortoise_tts.py [-h] [-v, --voice VOICE] [-V, --voices-dir VOICES_DIR]
[-p, --preset {ultra_fast,fast,standard,high_quality}] [-q, --quiet]
(-l, --list-voices | -P, --play | -o, --output OUTPUT | -O, --output-dir OUTPUT_DIR)
[--candidates CANDIDATES] [--regenerate REGENERATE] [--skip-existing]
[--produce-debug-state] [--seed SEED] [--models-dir MODELS_DIR]
[--text-split TEXT_SPLIT] [--disable-redaction]
[--num-autoregressive-samples NUM_AUTOREGRESSIVE_SAMPLES]
[--temperature TEMPERATURE] [--length-penalty LENGTH_PENALTY]
[--repetition-penalty REPETITION_PENALTY] [--top-p TOP_P]
[--max-mel-tokens MAX_MEL_TOKENS] [--cvvp-amount …
```
> Add CLI tool

- tortoise/read.py
If candidates were greater than 1 on in read.py, only the first candidate clips would be combined. This adds a bit of code to make a combined file for every candidate.
> read.py combines all candidates

- README.md
- requirements.txt
This PR updates the dependencies such that `numpy` is locked at 1.20.0 to ensure that the project does not accidentally run afoul of the `numpy.long` deprecation. It also adds a few other dependencies that *appear* to be necessary for proper installation.
Additionally it updates the documentation such that the dependency requirements specified in `requirements.txt` are actually followed - when I used the `python setup.py install` directions, the version requirements in `requirements.txt` were not obeyed, and my environment just installed the latest version of all deps (including `number`), which I believe was causing issues similar to what was seen in [this issue](https://github.com/neonbjb/tortoise-tts/issues/240).
> Documentation and Dependency Updates

- requirements.txt
Found while reviewing my code.
In retrospect I thought the necessity of the `ffmpeg` requirement from prior seemed odd. I had copied / pasted the req from someone else's thoughts on using `tortoise-tts`, and didn't question. After reviewing the dependencies I added to make sure they were all reasonably required within sub-projects, the `ffmpeg` dependency stood out as likely unnecessary ( Presuming it is [this library](https://github.com/jiashaokun/ffmpeg), it does not seem to actually be invoked by any libraries used in tortoise tts' operation ). 
My apologies for the bad suggestion here, removing the dependency to prevent any unnecessary inclusion.
> Remove FFMPEG dep

- requirements.txt
- setup.py
setup.py wasn't pinned
credits to [n8bot](https://github.com/n8bot)
This affects:
https://github.com/neonbjb/tortoise-tts/issues/472
https://github.com/neonbjb/tortoise-tts/issues/476
https://github.com/neonbjb/tortoise-tts/issues/479
https://github.com/neonbjb/tortoise-tts/issues/480
> Pin transformers==4.29.2 (upgrade) and fix for setup.py #472 #476 #479 #480

- requirements.txt
Fixes this issue that I'm running into: https://stackoverflow.com/questions/72364077/pydantic-setting-a-default-value-for-an-annotated-type
Stacktrace with 1.9.0:
```
╰─ python tortoise/do_tts.py --text "I'm going to speak this" --preset fast …
```
> Update pydantic to 1.9.1 to fix ValueError

- setup.py
Noticed this when trying to install the repo as a package (pip fails to upgrade if it's the same).
Also some of the dependencies _might_ be added to setup.py, depending on how well they install. If they have installation problems, leaving them optional is a good choice as well.
> bump minor version in setup.py

- README.md
I needed to do this to get `do_tts.py` to work on an apple m2.
> Add psutil to apple instructions

- tortoise/models/hifigan_decoder.py
Allow higigan_decoder.py to run when not using a GPU. Added statements so it detects if you have CUDA or not to set the device in its return statement.
> Add CPU only support to hifigan_decoder.py

- tortoise/utils/audio.py
Avoid execution failures due to file extension case differences
> Make voice file extension comparison case-insensitive

- tortoise/api.py
- tortoise/utils/audio.py
Changes made prevent redundant initialization of TacotronSTFT within audio.wav_to_univnet_mel. 
Timing shows this dramatically reduces latency when using the api interface (latency reduced linearly for the number of provided voice samples).
> Preventing redundant initialization of TacotronSTFT

- Dockerfile
Building the docker image using `docker build . -t tts` didn't work for me, it gave the following error :
`error: tokenizers 0.15.1 is installed but tokenizers!=0.11.3,<0.14,>=0.11.1 is required by {'transformers'}`
I checked `requirements.txt` and found that the required transformers version was 4.31.0 instead of 4.29.2. After updating that line in the Dockerfile, the `docker build` command worked.
> Dockerfile - updated transformers version to 4.31.0

- Dockerfile
With the current Docker build, `conda` defaults to installing `pytorch` in CPU mode despite the use of pytorch and nvidia channels. This may be a change in how `conda` handles package relationships. The below command adjustment passes in the specific version numbers, which ensures that `conda` recognizes the use of `pytorch-cuda` as related, and properly installs the CUDA version of `pytorch`.
This can be validated after-the-fact with starting the container and running:
```bash
cd /app
conda activate tortoise
python -c "import torch; print(torch.cuda.is_available());torch.zeros(1).cuda()"
```
The current image returns an error, while after this PR, returns "True".
Note: This also updates CUDA in pytorch to 12.1 to better align to the CUDA docker image being used as the base.
> Update Dockerfile to enable CUDA pytorch

- tortoise/api.py
- tortoise/api_fast.py
This fixes issue #776. 
Without this fix, you wouldn't be able to select cpu even if you wanted to use it in a system with both cpu and gpu. 
Also, for multi GPU systems, not being able to specify a GPU device will trigger cuda errors if the voice clips/inputs/model are loaded on separate devices.
> adding a parameter check for device.

- setup.cfg
setuptools is deprecating dash-separated options on 2024-09-26.  There's a banner when installing that warns about this.
> setup.cfg: fix warning

- Dockerfile
- setup.py
This fixes two issues I've encountered when building my docker container:
1. #799 
Here, I just replaced the versions of scipy and tokenizers with the working ones.
3. Conda being stuck on Proceed ([y]/n)? when installing packages and creating a conda environment.
Here, I added the `--yes` flags to the conda commands.
> Fixing issues with Docker Setup

- README.md
Highlighting the Conda installation method in a Tip box can really make the users more likely to succeed and not waste time struggling with dependencies.
> Two Minor Changes, Visually Appealing README.
